- name:        ioannis.mk
  remote_user: postgres
  become:      yes
  copy:        src=src/ioannis.mk  dest="{{ HOME }}/postgres/src"

    
################### git postgresql ############################
- name:        git postgres
  remote_user: postgres
  become:      yes
  register:    github_postgres_success
  git:  
     repo:        https://github.com/postgres/postgres.git
     #repo: https://github.com/reorg/pg_repack.git
     dest:      "{{ HOME }}/postgres/src/postgres"
     version:   "{{ postgres_checkout }}"

################### Other Repos ############################
- include:    github_repos.yml
  when:       github_repos


- name:         chown -R ~postgres/src
  become_user:  root
  become:       yes
  command:      chown -R postgres:postgres  ~postgres/src/postgres
  environment:  PATH="/bin:/usr/bin:/usr/local/bin"


- name:          update github postgres
  ignore_errors: True
  when:          false
  git:
    repo:       https://github.com/postgres/postgres.git
    dest:       "{{ HOME }}/postgres/src/postgres"
    update:     yes
    clone:      no
    force:      yes

################### Configure ############################

- name:        ./configure postgres (Debian)
  when:        ansible_os_family == 'Debian'
  command:     "./configure   --with-includes=/opt/local/include  --with-libs=/opt/local/lib --prefix={{ HOME }}/postgres/pg-{{ postgres_checkout }}   --with-openssl   --with-ldap  chdir={{ HOME }}/postgres/src/postgres"

- name:      ./configure postgres (FreeBSD)
  when:      os_family == 'FreeBSD'
  command:   "./configure  --without-readline  --prefix={{ HOME }}/postgres/pg-{{ postgres_checkout }}   --with-openssl   --with-libxml --with-pam  chdir={{ HOME }}/postgres/src/postgres"

- name:      ./configure  postgres (Darwin)
  when:      os_family == 'Darwin'
  command:   "./configure   --with-includes=/opt/local/include   --with-libs=/opt/local/lib  --prefix={{ HOME }}/postgres/pg-{{ postgres_checkout }}   --with-openssl   --with-pam --with-ldap  chdir={{ HOME }}/postgres/src/postgres"

################### Compile postgres ############################
- name:      make
  make:      target="install"      chdir="{{ HOME }}/postgres/src/postgres" 

- name:      make install-docs
  make:      target="install-docs"      chdir="{{ HOME }}/postgres/src/postgres" 
  when:      install_docs

- name:      "ln -sf ~/pg-{{ postgres_checkout }}  ~/dist-pg"
  file:      src="{{ HOME}}/postgres/pg-{{ postgres_checkout  }}"  dest="{{ HOME}}/postgres/dist-pg"  owner=postgres   state=link    

