- name:           packages to compile postgres sources
  become_user:    root
  become:         yes
  apt:
     pkg:
                  - bison
                  - flex
                  - zlib1g-dev
                  - libreadline-dev 
                  - libssl-dev
                  - libpam0g-dev
                  - libxml2-dev
                  - libxslt1.1
                  - libxslt1-dev
                  - libldap2-dev
                  - pkg-config
                  - libicu-dev
                  - libxml2-utils
                  - xsltproc
                  - pgxnclient
                  - cmake
                  - libevent-dev
                  - pandoc
                  - libtool

