#################################       verify  link 'dist-pg' is pointing to {{ postgres_checkout }}
- stat:    path="{{ HOME }}/postgres/dist-pg"
  register: sym

- name:      fail if symlink does not exist
  assert: 
     that:          sym.stat.exists and  sym.stat.islnk
     fail_msg:      msg="symlink ~postgres/dist-pg  not found"

- shell:     '/bin/ls -l ~postgres/dist-pg'
  register:  ls

- set_fact:    actual_pgdir="{{ ls.stdout.split('->')[1] }}"


- name:     symlink  points to correct dir
  assert:      
     fail_msg: "symlink ~postgres/dist-pg  points to \"{{ actual_pgdir }}\" instead of \"{{ postgres_checkout }}\""
     that: 
        -   postgres_checkout  in  actual_pgdir

