    
- name:       extra packages
  include:    "{{ ansible_os_family }}.yml"
  become_user: root
  become:      yes
  when:        false


- include: compile.yml
  become_user: postgres
  become:      yes

- include:     timescaledb.yml
  become_user: postgres
  become:      yes
  when:        compile_timescaledb
  
  ########################################### Post Install
- include:   "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_hostname }}.yml"
      skip: true

