################################################# Helper Variables
- command:      uname -s
  environment:  PATH="/bin:/usr/bin:/usr/local/bin"
  register:     result

- set_fact:     os_family="{{result.stdout}}"

- set_fact:     HOME="/home"
  when:         os_family == "Linux"

- set_fact:     HOME="/Users"
  when:         os_family == "Darwin"

- set_fact:     HOME="/home"
  when:         os_family == "FreeBSD"

- command:      whoami
  environment:  PATH="/bin:/usr/bin:/usr/local/bin"
  register:     WHOAMI
################################################################# 
- name:        fail unless ansible executing as unix user postgres
  when:        not (  WHOAMI.stdout  == "postgres")
  fail:        msg="Detected '{{ WHOAMI.stdout }}', but must run as 'postgres'"

- name:        /var/log/postgres
  become_user: root
  become:      yes
  file:        path=/var/log/postgresql   state=directory   owner=postgres   group=postgres   mode=0750 

- name:       ~postgres/src
  file:       path="{{ HOME }}/postgres/src"   owner=postgres  group=postgres  group=postgres  state=directory

  ##################################################################
- name:         packages
  include:     "{{ ansible_os_family }}.yml"
  become_user:  root
  become:       yes
  when:         false

- include: compile.yml
  become_user:  postgres
  become:       yes
  when:         compile_postgres


#################################       verify  link 'dist-pg' is pointing to {{ postgres_checkout }}

- stat:    path="/home/postgres/dist-pg"
  register: sym

- name:      fail if symlink does not exist
  when:      (sym.stat.islnk is undefined) or (not  sym.stat.islnk)
  fail:      msg="symlink ~postgres/dist-pg does not exist"

- shell:     '/bin/ls -l ~postgres/dist-pg'
  register:  ls

- set_fact:    actual_pgdir="{{ ls.stdout.split('->')[1] }}"

- name:      symlink should point to correct dir
  fail:      msg="symlink ~postgres/dist-pg  points to \"{{ actual_pgdir }}\" instead of \"{{ postgres_checkout }}\" "
  when:    
     -   actual_pgdir !=   " pg-{{  postgres_checkout }}"

# Skip timescaldeb if already installed
- stat:      path="{{ HOME }}/postgres/dist-pg/share/extension/timescaledb.control"
  register:  ts_control
 #############################################################


- include:      timescaledb.yml
  become_user:  postgres
  become:       yes
  when:     
     -  compile_timescaledb
     -  not ts_control.stat.exists
  
- include:      extensions.yml
  become_user:  postgres
  become:       yes
  when:         compile_extensions


##################################################### Post Install
- include:     "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_hostname }}.yml"
      skip: true

