
################### git pgaudit ############################

- name:           rm ~/src/pgaudit
  file:           dest="{{ HOME }}/postgres/src/pgaudit"    state=absent


- name:        git pgaudit
  remote_user: postgres
  become:      yes
  git:  
     repo:       https://github.com/2ndQuadrant/pgaudit.git
     dest:      "{{ HOME }}/postgres/src/pgaudit"


- name:          update github pgaudit
  ignore_errors: True
  git:
     repo:       https://github.com/2ndQuadrant/pgaudit.git
     dest:       "{{ HOME }}/postgres/src/pgaudit"
     update:     yes
     clone:      no
     force:      yes



- name:            chown -R ~postgres/src/pgaudit
  become_user:     root
  become:          yes
  command:         chown -R postgres:postgres  ~postgres/src/timescaledb
  environment:  
      PATH:                    "/bin:/usr/bin:/usr/sbin"
  

################### Compile pgaudit ############################

- name:           make
  make:           target="install"      chdir="{{ HOME }}/postgres/src/pgaudit"
  environment:  
      PATH:                 "{{ HOME }}/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"
      PG_PATH:              "{{ HOME }}/postgres/dist-pg/bin"
      USE_PGXS:              1



