#################################       verify  link 'dist-pg' is pointing to {{ postgres_checkout }}
- stat:    path="{{ HOME }}/postgres/dist-pg"
  register: sym

- name:      fail if symlink does not exist
  when:      (sym.stat.islnk is undefined) or (not  sym.stat.islnk)
  fail:      msg="symlink ~postgres/dist-pg does not exist"

- shell:     '/bin/ls -l ~postgres/dist-pg'
  register:  ls

- set_fact:    actual_pgdir="{{ ls.stdout.split('->')[1] }}"

- name:      symlink should point to correct dir
  fail:      msg="symlink ~postgres/dist-pg  points to \"{{ actual_pgdir }}\" instead of \"{{ postgres_checkout }}\" "
  when:    
     -   actual_pgdir !=   " pg-{{  postgres_checkout }}"
     -   compile_timescaledb


################### git timescaledb ############################
- name:        git timescaledb
  remote_user: postgres
  become:      yes
  git:  
     repo:       https://github.com/timescale/timescaledb.git
     dest:      "{{ HOME }}/postgres/src/timescaledb"
     #version:   'master'

################### Other Repos ############################

- name:          update github tiscaledb
  ignore_errors: True
  git:
    repo:       https://github.com/timescale/timescaledb.git
    dest:       "{{ HOME }}/postgres/src/timescaledb"
    update:     yes
    clone:      no
    force:      yes


################### Configure ############################


- name:           no previous build exits
  file:           dest="{{ HOME }}/postgres/src/timescaledb/build"    state=absent


- name:           ./bootstrap timescaledb
  shell:          "cd ~postgres/src/timescaledb && ./bootstrap -DREGRESS_CHECKS=OFF "
  #when:           ansible_os_family == 'Debian'
  environment:  
      PATH:                 "{{ HOME }}/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"
      PG_PATH:              "{{ HOME }}/postgres/dist-pg/bin"
      BUILD_FORCE_REMOVE:   true


- name:            chown -R ~postgres/src/timescaledb
  become_user:     root
  become:          yes
  command:         chown -R postgres:postgres  ~postgres/src/timescaledb
  environment:  
      PATH:                    "/bin:/usr/bin:/usr/sbin"
  
################### Compile timescale ############################

- name:      make   timescaledb
  make:      target="install"      chdir="{{ HOME }}/postgres/src/timescaledb/build"
  environment:  
      PATH:                 "{{ HOME }}/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"



