################### git timescaledb ############################
- name:        git timescaledb
  remote_user: postgres
  become:      yes
  git:  
     repo:       https://github.com/timescale/timescaledb.git
     dest:      "{{ HOME }}/postgres/src/timescaledb"
     #version:   'master'

################### Other Repos ############################

- name:          update github tiscaledb
  ignore_errors: True
  git:
    repo:       https://github.com/timescale/timescaledb.git
    dest:       "{{ HOME }}/postgres/src/timescaledb"
    update:     yes
    clone:      no
    force:      yes


################### Configure ############################


- name:           no previous build exits
  when:           ansible_os_family == 'Debian'
  file:           dest="/home/postgres/src/timescaledb/build"    state=absent


- name:           ./bootstrap timescaledb
  shell:          "cd ~postgres/src/timescaledb && ./bootstrap -DREGRESS_CHECKS=OFF "
  environment:  
      PATH:                 "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"
      BUILD_FORCE_REMOVE:   true


- name:            chown -R ~postgres/src/timescaledb
  become_user:     root
  become:          yes
  command:         chown -R postgres:postgres  ~postgres/src/timescaledb
  environment:  
      PATH:                    "/bin:/usr/bin:/usr/sbin"
  
################### Compile timescale ############################

- name:      make
  make:      target="install"      chdir="/home/postgres/src/timescaledb/build"
  environment:  
      PATH:                 "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"



